"""
Django settings for hasker project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from split_settings.tools import optional, include
from os import environ

ENV = environ.get('DJANGO_ENV') or 'development'

base_settings = [
    'components/secret.py',
    'components/common.py',  # standard django settings
    'components/db.py',  # postgres
    'components/apps.py',
    'components/email.py',  # smtp

    # Select the right env:
    'environments/%s.py' % ENV,
    
    # Optionally override some settings:
    optional('environments/local.py'),
]

# Include settings:
include(*base_settings)

